# Generated by Django 4.2.7 on 2025-11-21 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('developer_id', models.AutoField(db_column='DeveloperID', primary_key=True, serialize=False)),
                ('developer_name', models.CharField(db_column='DeveloperName', max_length=255)),
            ],
            options={
                'db_table': 'Developers',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(db_column='GameID', primary_key=True, serialize=False)),
                ('game_name', models.CharField(db_column='GameName', max_length=255)),
                ('game_price', models.DecimalField(blank=True, db_column='GamePrice', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(db_column='GenreID', primary_key=True, serialize=False)),
                ('genre_name', models.CharField(db_column='GenreName', max_length=100)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('budget', models.DecimalField(blank=True, db_column='Budget', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='GameSystemRequirements',
            fields=[
                ('game', models.OneToOneField(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.games')),
                ('cpu_requirements', models.CharField(blank=True, db_column='CPURequirements', max_length=255, null=True)),
                ('gpu_requirements', models.CharField(blank=True, db_column='GPURequirements', max_length=255, null=True)),
                ('ram_requirements', models.CharField(blank=True, db_column='RAMRequirements', max_length=255, null=True)),
            ],
            options={
                'db_table': 'GameSystemRequirements',
            },
        ),
        migrations.CreateModel(
            name='UserSpecs',
            fields=[
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.users')),
                ('cpu', models.CharField(blank=True, db_column='CPU', max_length=255, null=True)),
                ('gpu', models.CharField(blank=True, db_column='GPU', max_length=255, null=True)),
                ('ram', models.CharField(blank=True, db_column='RAM', max_length=100, null=True)),
            ],
            options={
                'db_table': 'UserSpecs',
            },
        ),
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.ForeignKey(db_column='GenreID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genres'),
        ),
        migrations.CreateModel(
            name='CreatedGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(db_column='DateCreated')),
                ('developer', models.ForeignKey(db_column='DeveloperID', on_delete=django.db.models.deletion.CASCADE, to='core.developers')),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
            ],
            options={
                'db_table': 'CreatedGames',
            },
        ),
        migrations.CreateModel(
            name='UserWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'UserWishList',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='UserFavoritedGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.CASCADE, to='core.genres')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'UserFavoritedGenres',
                'unique_together': {('user', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('review_text', models.TextField(db_column='ReviewText')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
            ],
            options={
                'db_table': 'Reviews',
                'indexes': [models.Index(fields=['game'], name='Reviews_GameID_abfa82_idx'), models.Index(fields=['-created_at'], name='Reviews_Created_8821bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='games',
            index=models.Index(fields=['game_name'], name='Games_GameNam_73b0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='games',
            index=models.Index(fields=['genre'], name='Games_GenreID_9d2164_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='createdgames',
            unique_together={('developer', 'game')},
        ),
    ]
