# Generated by Django 4.2.7 on 2025-11-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='release_year',
            field=models.IntegerField(blank=True, db_column='ReleaseYear', null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='storage_gb',
            field=models.FloatField(blank=True, db_column='StorageGB', null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='author_playtime_forever',
            field=models.IntegerField(blank=True, db_column='AuthorPlaytimeForever', null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='voted_up',
            field=models.BooleanField(blank=True, db_column='VotedUp', null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='votes_funny',
            field=models.IntegerField(db_column='VotesFunny', default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='votes_up',
            field=models.IntegerField(db_column='VotesUp', default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='word_count',
            field=models.IntegerField(blank=True, db_column='WordCount', null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt'),
        ),
    ]
