# Generated by Django 4.2.7 on 2025-12-02 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_games_release_year_games_storage_gb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUrls',
            fields=[
                ('game', models.OneToOneField(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.games')),
                ('url', models.CharField(db_column='URL', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Game URLs',
                'db_table': 'gameUrls',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('plat_id', models.AutoField(db_column='PlatID', primary_key=True, serialize=False)),
                ('platform_name', models.CharField(db_column='PlatformName', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Platforms',
                'db_table': 'Platform',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('pub_id', models.AutoField(db_column='PubID', primary_key=True, serialize=False)),
                ('publisher', models.CharField(db_column='Publisher', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Publishers',
                'db_table': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(db_column='TagID', primary_key=True, serialize=False)),
                ('tag_string', models.CharField(db_column='TagString', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='createdgames',
            options={'verbose_name_plural': 'Created Games'},
        ),
        migrations.AlterModelOptions(
            name='developers',
            options={'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='userfavoritedgenres',
            options={'verbose_name_plural': 'User Favorited Genres'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userspecs',
            options={'verbose_name_plural': 'User Specs'},
        ),
        migrations.AlterModelOptions(
            name='userwishlist',
            options={'verbose_name_plural': 'User Wish Lists'},
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(db_column='PurchaseDate')),
                ('price_paid', models.DecimalField(db_column='PricePaid', decimal_places=2, max_digits=10)),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'verbose_name_plural': 'User Libraries',
                'db_table': 'userLibrary',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_supported', models.CharField(db_column='LanguageSupported', max_length=255)),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'Languages',
                'unique_together': {('game', 'language_supported')},
            },
        ),
        migrations.CreateModel(
            name='GameTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
                ('tag', models.ForeignKey(db_column='TagID', on_delete=django.db.models.deletion.CASCADE, to='core.tags')),
            ],
            options={
                'verbose_name_plural': 'Game Tags',
                'db_table': 'gameTags',
                'unique_together': {('game', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='GamePublishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(db_column='PublishDate')),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
                ('publisher', models.ForeignKey(db_column='PubID', on_delete=django.db.models.deletion.CASCADE, to='core.publishers')),
            ],
            options={
                'verbose_name_plural': 'Game Publishers',
                'db_table': 'gamePublishers',
                'unique_together': {('game', 'publisher')},
            },
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
                ('platform', models.ForeignKey(db_column='PlatID', on_delete=django.db.models.deletion.CASCADE, to='core.platform')),
            ],
            options={
                'verbose_name_plural': 'Game Platforms',
                'db_table': 'gamePlatform',
                'unique_together': {('game', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(db_column='ImageURL', max_length=500)),
                ('game', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='core.games')),
            ],
            options={
                'verbose_name_plural': 'Game Images',
                'db_table': 'gameImages',
                'unique_together': {('game', 'image_url')},
            },
        ),
    ]
